import React from 'react';
import {AbsoluteFill,Audio,Composition,Img,OffthreadVideo,Sequence,interpolate,registerRoot,staticFile,useCurrentFrame} from 'remotion';
import {MaskRevealUp} from './components/remocn/mask-reveal-up';

const C={bg:'#0b151f',panel:'#142432',white:'#f3f7fa',muted:'#96aebf',orange:'#ff9900',cyan:'#67d7f4'};
const fps=30;
const motionClips:Record<string,string>={'mobile-after':'home-motion','mobile-after-app':'mobile-globe-motion','insights-mobile':'phone-insights-action-clean',heroes:'heroes-action',insights:'insights-action-clean',lofts:'lofts-action',calendar:'calendar-action',ambassadors:'ambassadors-action','submission-open':'submission-action'};
const ease=(f:number,a:number,b:number)=>interpolate(f,[a,b],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
function Still({name,style={}}:{name:string;style?:React.CSSProperties}){return <Img src={staticFile(name+'.png')} style={{width:'100%',height:'100%',objectFit:'contain',...style}}/>}
function Phone({name,label}:{name:string;video?:boolean;label?:string}){
 const f=useCurrentFrame(),entry=ease(f,0,24),file=motionClips[name];
 return <div style={{display:'flex',flexDirection:'column',alignItems:'center',gap:16,transform:`translateY(${(1-entry)*22+Math.sin(f/48)*3}px) scale(${.985+entry*.015})`,opacity:entry}}>
 {label&&<div style={{fontSize:24,color:label.startsWith('Now')?C.cyan:C.muted}}>{label}</div>}
 <div style={{width:320,height:692,border:'2px solid #3a5161',borderRadius:30,overflow:'hidden',background:C.bg,boxShadow:'0 22px 60px #0007'}}>
 {file?<OffthreadVideo src={staticFile(file+'.mp4')} startFrom={name==='mobile-after-app'?90:0} playbackRate={name==='mobile-after'?1.5:1} muted style={{width:'100%',height:'100%',objectFit:'cover'}}/>:<Still name={name==='mobile-before-app'?'july-before-motion':name}/>}
 </div></div>
}
function Shell({n,title,sub,children}:{n:string;title:string;sub:string;children:React.ReactNode}){const f=useCurrentFrame();return <AbsoluteFill style={{background:C.bg,color:C.white,fontFamily:'Arial, sans-serif',padding:'52px 80px',opacity:interpolate(f,[0,12],[0,1],{extrapolateRight:'clamp'})}}><div style={{display:'flex',justifyContent:'space-between',alignItems:'center',fontSize:24,letterSpacing:1}}><div><b style={{color:C.orange}}>AWS</b> <b>Globe</b></div><span style={{color:C.muted,fontSize:18}}>WHAT’S NEW · SEPTEMBER 2026</span></div><div style={{marginTop:35,display:'flex',gap:25,alignItems:'baseline'}}><span style={{color:C.orange,fontSize:22}}>{n}</span><h1 style={{fontSize:48,letterSpacing:-1.5,margin:0}}>{title}</h1></div><p style={{fontSize:25,color:C.muted,margin:'14px 0 28px'}}>{sub}</p>{children}<div style={{position:'absolute',bottom:23,left:80,right:80,height:2,background:'#263947'}}/><span style={{position:'absolute',bottom:30,right:80,fontSize:14,color:C.muted}}>AWS community project · Development preview</span></AbsoluteFill>}
function Screen({name,video=false}:{name:string;video?:boolean}){
 const f=useCurrentFrame(),file=motionClips[name],entry=ease(f,0,22),zoom=1+ease(f,25,230)*.022;
 return <div style={{width:1190,height:744,position:'absolute',right:80,top:264,borderRadius:14,overflow:'hidden',border:'1px solid #3a5161',background:C.bg,transform:`translateY(${(1-entry)*22}px) scale(${.99+entry*.01})`,opacity:entry}}><div style={{width:'100%',height:'100%',transform:`scale(${zoom})`,transformOrigin:'50% 45%'}}>
 {file||video?<OffthreadVideo src={staticFile((file||name)+'.mp4')} startFrom={file?0:135} muted style={{width:'100%',height:'100%',objectFit:'contain'}}/>:<Still name={name}/>}
 </div></div>
}
function Notes({lines,foot}:{lines:string[];foot?:string}){const f=useCurrentFrame();return <div style={{position:'absolute',left:80,top:370,width:430}}>{lines.map((t,i)=><div key={t} style={{marginBottom:40,fontSize:31,lineHeight:1.3,opacity:ease(f,8+i*8,24+i*8),transform:`translateX(${(1-ease(f,8+i*8,24+i*8))*-18}px)`}}><div style={{width:32,height:3,background:i%2?C.cyan:C.orange,marginBottom:17}}/>{t}</div>)}{foot&&<p style={{fontSize:20,lineHeight:1.5,color:C.muted}}>{foot}</p>}</div>}
function Intro(){return <Shell n="" title="Your community. A whole new view." sub="A refreshed AWS Globe, built for exploring everywhere."><div style={{position:'absolute',left:80,top:330,width:950,height:330}}><MaskRevealUp text={'More to discover.\nBetter on mobile.'} fontSize={76} color={C.white}/></div><div style={{position:'absolute',right:220,top:270}}><Phone name="mobile-after"/></div><div style={{position:'absolute',left:180,top:730,color:C.orange,fontSize:25}}>THE SEPTEMBER UPDATE</div></Shell>}
function Compare({app=false}:{app?:boolean}){return <Shell n="01" title={app?'A clearer view inside the globe.':'A new first impression on mobile.'} sub={app?'A layout built for your phone. Categories, filters and suggestions within reach.':'A live community globe and a clearer way to start exploring.'}><div style={{display:'flex',gap:65,position:'absolute',left:270,top:282}}><Phone name={app?'mobile-before-app':'mobile-before'} label={app?"Before · July 6":"Before · August 24"}/><Phone name={app?'mobile-after-app':'mobile-after'} label="Now · September update"/></div><div style={{position:'absolute',right:100,top:430,width:500,fontSize:39,lineHeight:1.4}}>{app?'Discover nearby people, then help us add anyone we missed.':'From a long introduction to a globe you can explore.'}<p style={{fontSize:22,color:C.muted,lineHeight:1.5,marginTop:35}}>Real captures at the same 390 × 844 mobile viewport.</p></div></Shell>}
function Video(){return <AbsoluteFill><Audio src={staticFile('soundtrack.wav')} volume={0.8}/>
 <Sequence from={0} durationInFrames={150}><Intro/></Sequence>
 <Sequence from={150} durationInFrames={240}><Compare/></Sequence>
 <Sequence from={390} durationInFrames={210}><Compare app/></Sequence>
 <Sequence from={600} durationInFrames={240}><Shell n="02" title="A clearer globe, even when it gets busy." sub="Grouped markers reveal more detail as you zoom."><Notes lines={['Explore crowded areas','Keep every profile available']} foot="Open a group to discover the people behind each marker."/><Screen name="heroes" video/></Shell></Sequence>
 <Sequence from={840} durationInFrames={240}><Shell n="03" title="Meet the new Insights." sub="The website’s navy, cyan and orange palette — now across your analytics."><Notes lines={['Explore regional patterns','Browse one snapshot per month','Readable date controls']}/><Screen name="insights" video/></Shell></Sequence>
 <Sequence from={1080} durationInFrames={210}><Shell n="04" title="Discover AWS Builder Lofts." sub="Find locations around the world and check their current status."><Notes lines={['San Francisco is open','Berlin, Hyderabad and São Paulo are announced']} foot="Official details and event links are available for each location."/><Screen name="lofts" video/></Shell></Sequence>
 <Sequence from={1290} durationInFrames={150}><Shell n="05" title="More Kiro Ambassadors to discover." sub="The directory grows from two to seven researched profiles."><Notes lines={['New people across the globe','Public sources linked to profiles']}/><Screen name="ambassadors"/></Shell></Sequence>
 <Sequence from={1440} durationInFrames={210}><Shell n="06" title="Make room for your next event." sub="Add to Calendar is available across event cards and Insights."><Notes lines={['Download an .ics calendar file','Import into your preferred calendar']} foot="Daily RSS refresh is configured; it activates after publication."/><Screen name="calendar" video/></Shell></Sequence>
 <Sequence from={1650} durationInFrames={210}><Shell n="07" title="Help the community fill the gaps." sub="Suggest a missing profile or event from the new + button."><Notes lines={['Share an official source','Review your suggestion on GitHub']} foot="Suggestions are reviewed before becoming directory entries."/><Screen name="submission-open"/></Shell></Sequence>
 <Sequence from={1860} durationInFrames={150}><Shell n="08" title="Small details. A more connected experience." sub="Floating section labels, clearer controls and responsive pages."><div style={{position:'absolute',left:290,top:286}}><Phone name="mobile-after" video/></div><div style={{position:'absolute',left:870,top:286}}><Phone name="insights-mobile"/></div></Shell></Sequence>
 <Sequence from={2010} durationInFrames={150}><Shell n="" title="Explore the update." sub="AWS Globe · September 2026"><div style={{position:'absolute',left:140,top:330,width:1640,height:310}}><MaskRevealUp text={'Find your people.\nDiscover your next event.'} fontSize={82} color={C.white}/></div><div style={{position:'absolute',top:775,width:1760,textAlign:'center',fontSize:29,color:C.cyan}}>github.com/Jagatees/aws-community-world</div><div style={{position:'absolute',top:838,width:1760,textAlign:'center',fontSize:19,color:C.muted}}>Before: July 6 globe · August 24 home · Current: September update</div></Shell></Sequence>
 </AbsoluteFill>}
registerRoot(()=> <Composition id="UpdateVideo" component={Video} width={1920} height={1080} fps={fps} durationInFrames={2160}/>);
